mira-amm/mira-amm-web

package-lock.json
package.json
src/core/providers/FuelProviderWrapper.tsx

- Fixed connectors config by passing the correct chainId to the external connectors.
- Updated `fuels` , `@fuels/connectors` , `@fuels/react` to latest
```
LICENSE:
The Fuel Support team submits this PR to help you use the fuel SDKs. It is provided "as is"
and without warranty for any purpose. We are not participants in the project at hand.
All the rights of this code are reserved to the authors of this repository.
```

fix: Fuel Connectors config  + update ts-sdk / connectors

---

src/components/pages/add-liquidity-page/AddLiquidityPageLayout.tsx
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.tsx
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePoolItem/MobilePoolItem.tsx
src/components/pages/view-position-page/ViewPositionPageLayout.tsx
src/components/pages/view-position-page/components/PositionView/PositionView.module.css
src/components/pages/view-position-page/components/PositionView/PositionView.tsx
src/hooks/usePoolsData.ts
src/utils/common.ts

fix: filter out invalid pools, correct poolId validity on add/show LP

---

src/components/common/Header/Header.module.css
src/components/common/Header/Header.tsx
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePoolItem/MobilePoolItem.tsx
src/hooks/usePoolsData.ts
src/utils/constants.ts

Closes https://github.com/mira-amm/mira-amm-web/issues/115
Watch Video: [Video](https://www.loom.com/share/a9378768c8694252a56eba1f589649d9?from_recorder=1&focus_title=1)
Release Banner:

Promo banner

---

.prettierrc
.vscode/settings.json

Closes https://github.com/mira-amm/mira-amm-web/issues/111

Setup Prettier

---

package-lock.json
package.json
src/components/common/Info/Info.tsx
src/components/common/InfoBlock/InfoBlock.module.css
src/components/common/Pagination/Pagination.module.css
src/components/common/Pagination/Pagination.tsx
src/components/common/SearchBar/SearchBar.module.css
src/components/common/SearchBar/SearchBar.tsx
src/components/common/SearchBar/SearchBarProps.ts
src/components/common/SortableColumn/SortableColumn.module.css
src/components/common/SortableColumn/SortableColumn.tsx
src/components/icons/ArrowDown/ArrowDownSmallIcon.tsx
src/components/icons/ArrowLeft/ArrowLeftIcon.tsx
src/components/icons/ArrowRight/ArrowRightIcon.tsx
src/components/icons/ArrowUp/ArrowUpSmallIcon.tsx
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPoolRow.tsx
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.module.css
src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.tsx
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePoolItem/MobilePoolItem.module.css
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePoolItem/MobilePoolItem.tsx
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePools.module.css
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePools.tsx
src/components/pages/liquidity-page/components/Pools/Pools.module.css
src/components/pages/liquidity-page/components/Pools/Pools.tsx
src/components/pages/liquidity-page/components/Pools/usePoolDetails.ts
src/core/providers/Providers.tsx
src/hooks/useDebounce.ts
src/hooks/usePoolsData.ts

Partially fixes https://github.com/mira-amm/mira-amm-web/issues/99
Watch video: [See Video](https://www.loom.com/share/dac42a3b5b484be888a0db60812a115e)
See progress/todo list here: https://github.com/mira-amm/mira-amm-web/issues/99#issue-2715245356

Liquidity page pagination

---

src/components/common/Footer/Footer.tsx

https://github.com/mira-amm/mira-amm-web/issues/124

Changed footer email to help@mira.ly

---

src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.tsx
src/components/pages/liquidity-page/components/Pools/MobilePools/MobilePools.tsx

Closes https://github.com/mira-amm/mira-amm-web/issues/142

Disable sorting by 24H volume

---

src/components/common/Pagination/Pagination.module.css

Closes https://github.com/mira-amm/mira-amm-web/issues/134
Before:
After:

Fix pagination icon size on mobile

---

src/utils/common.ts

Closes https://github.com/mira-amm/mira-amm-web/issues/149
https://www.loom.com/share/f9b378d149b243fe8c1e50c3f657cfd4?from_recorder=1&focus_title=1

Fix stable calculation

---

src/components/common/Swap/Swap.tsx
src/components/common/Swap/components/SwapFailureModal/SwapFailureModal.tsx

Closes https://github.com/mira-amm/mira-amm-web/issues/123

Review before swap

---

app/landing/layout.tsx
app/landing/page.tsx
app/layout.tsx
next.config.mjs
src/components/common/Header/Header.tsx

Closes https://github.com/mira-amm/mira-amm-web/issues/154

Remove the usage of landing page

---

src/components/common/Header/Header.tsx

Closes https://github.com/mira-amm/mira-amm-web/issues/155
https://www.loom.com/share/ded3459a9934474db995a91945d53a46?from_recorder=1&focus_title=1

Layout shifting fix for top blue banner

---

app/layout.tsx

Closes https://github.com/mira-amm/mira-amm-web/issues/167

Fix favicon

---

src/components/pages/view-position-page/components/PositionView/PositionView.module.css
src/components/pages/view-position-page/components/PositionView/PositionView.tsx

Closes https://github.com/mira-amm/mira-amm-web/issues/179

add boosted apr to liquidity screen

---

src/components/pages/liquidity-page/components/Boosts/BoostsRewards/BoostsRewards.tsx
src/utils/common.ts

https://github.com/mira-amm/mira-amm-web/pull/183
- Clean up unused function
- Updated calculateUsdValue function

Updated calculateUsdValue function and clean up

---

src/components/pages/view-position-page/components/PositionView/PositionView.tsx
src/components/pages/view-position-page/components/RemoveLiquidityModalContent/RemoveLiquidityModalContent.tsx
src/hooks/useRemoveLiquidity.ts

Closes https://github.com/mira-amm/mira-amm-web/issues/133
Before and after [video](https://amal-jose.neetorecord.com/watch/0d01882c4804c681fe3c)

Added loader for remove liquidity

---

src/components/common/Swap/Swap.tsx

Clear previousPreviewValue on different input

---

public/css/globals.css
src/components/common/Swap/Swap.tsx
src/components/common/Swap/components/CurrencyBox/CurrencyBox.tsx
src/hooks/useSwapPreview.ts

https://www.loom.com/share/2fdb8e141cd149269f2968ccde781581
Todo:
Closes https://github.com/mira-amm/mira-amm-web/issues/221
Closes https://github.com/mira-amm/mira-amm-web/issues/203
Closes https://github.com/mira-amm/mira-amm-web/issues/212

Fix swap button error and disable

---

.github/workflows/specs_test.yml

Closes https://github.com/mira-amm/mira-amm-web/issues/244

Add GitHub Actions workflow to run unit tests on push and pull request

---

src/components/common/ConnectButton/ConnectButton.tsx

Reverts mira-amm/mira-amm-web#242
Closes https://github.com/mira-amm/mira-amm-web/issues/255

Revert "Bugfix/wallet connection"

---

src/components/common/Info/Info.module.css
src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidity.module.css
src/components/pages/view-position-page/components/PositionView/PositionView.tsx
src/hooks/useRemoveLiquidity.ts

Closes [296](https://github.com/mira-amm/mira-amm-web/issues/296), [298](https://github.com/mira-amm/mira-amm-web/issues/298), [299](https://github.com/mira-amm/mira-amm-web/issues/299)

Fix/liquidity page UI

---

apps/web-e2e/src/index.spec.ts
src/components/pages/view-position-page/components/PositionView/PositionView.tsx

fix(ui/liquidity): closing remove liquidity success dialog redirects to `/liquidity`

---

.github/workflows/release.yml
package.json
pnpm-lock.yaml
release.config.ts

Closes #273.
- Need to auto-generate changelogs for our platform that adhere to the [Semver Spec](https://semver.org)
- Need to follow a standardized format for commits that can be parsed
- [Conventional Commits](https://www.conventionalcommits.org) is that format
- [Semantic Release](https://semantic-release.gitbook.io/semantic-release) is the parsing and changelog generation tool

ci(release): 273 create pipeline

---

package.json
pnpm-lock.yaml

Swaps were failing with the following error with this upgrade
```
9118-67281029a47b80e…XLTrXRfrgpkqHJcH8:9 Error: Cannot read properties of undefined (reading 'url')
at new r (92facbf4-da691f3c7b2…frgpkqHJcH8:1:68846)
at e.<anonymous> (92facbf4-da691f3c7b2…frgpkqHJcH8:1:72717)
at 92facbf4-da691f3c7b2…frgpkqHJcH8:1:71247
at Object.next (92facbf4-da691f3c7b2…frgpkqHJcH8:1:71352)
at s (92facbf4-da691f3c7b2…frgpkqHJcH8:1:70059)
```

Revert "chore(deps): upversion `@fuels{connectors,react}` and `fuels`"

---

libs/web/src/core/providers/FuelProviderWrapper.tsx
libs/web/src/hooks/useAssetMetadata.ts
libs/web/src/hooks/useCheckActiveNetwork.ts
libs/web/src/hooks/useProvider/useProvider.ts
package.json
pnpm-lock.yaml

| Before | After |
|-|-|
| ![image](https://github.com/user-attachments/assets/bbe3031e-467a-4b61-b48c-f0ead39033ca) | ![image](https://github.com/user-attachments/assets/130b4ce4-6839-497d-a489-ccba5ea78b40)  |

fix(web): swaps failing due to outdated fuels dependencies

---

.github/workflows/BUILD.yaml
libs/web/src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPoolRow.tsx

fix(ui/web/liquidity): no pointer on button hover

---

apps/web/app/(core)/page.tsx
libs/web/src/components/common/Swap/Swap.tsx
libs/web/src/components/common/connect-wallet-new.tsx
libs/web/src/components/common/header-new.tsx

Reverts mira-amm/mira-amm-web#433. Not the order of merging that I we should have used.

Revert "wip mobile styling past swap"

---

libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/V2LiquidityConfig.tsx

* Converted the min/max fields to text inputs with a debounced update.
* While typing, the input preserves the cursor position and your raw text.
* The value is only parsed and committed after a short pause, blur, or Enter key.
* This prevents the cursor from jumping and makes editing decimals work as expected.
https://www.loom.com/share/8c20652e9cd648cf81881c18a7db58f7?sid=355bf8c7-4544-4f84-b86d-1e02b647b01e

fix(web): max/min price field not working

---

libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/V2LiquidityConfig.tsx

This PR addresses the issue where entering an invalid price range (e.g. max lower than min, or min greater than max) caused negative bin counts and invalid state updates.
* Added explicit rangeError state.
* When an invalid number is entered:
* An error message is shown ("Invalid range. The min price must be lower than the max price.").
* No updates are applied to price range, simulation, or bin count.
* Inputs now clear the error on blur if no invalid value was committed, so the error doesn’t persist unnecessarily.
* Clicking into the Num Bins field while in error resets the price range and clears the error.
* Negative bins are no longer possible.
https://www.loom.com/share/77bba4e1069d4d098f9382a539af4f4f?sid=170dacde-33f9-40e1-acee-b71cf60d215f

fix(web): invalid range handling

---

libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/V2LiquidityConfig.tsx

When user has not added any deposit amounts we don’t render the simulation (and don’t compute it).
https://www.loom.com/share/7dba50f59f2944568608042b4b2bbae0?sid=21f14fc9-d9c3-4ce2-a215-144f0dd6e566

fix(web): hide simulation

---

libs/web/src/components/common/CoinPair/CoinPair.tsx
libs/web/src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPoolRow.tsx
libs/web/src/components/pages/liquidity-page/components/Pools/DesktopPools/DesktopPools.tsx
libs/web/src/components/pages/liquidity-page/components/Pools/ResponsivePools.tsx
libs/web/src/components/pages/liquidity-page/components/Positions/Positions.tsx
libs/web/src/components/pages/view-position-page/components/PositionView/PositionView.tsx
libs/web/src/components/pages/view-position-page/components/PositionView/desktop-position-view.tsx
libs/web/src/components/pages/view-position-page/components/PositionView/mobile-position-view.tsx
libs/web/src/hooks/usePositions.ts
libs/web/src/utils/poolTypeDetection.ts

Improve badge design for pool type
demo
https://www.loom.com/share/bfb7d5c131bc4c2a9551eb06c3d44fda?sid=ba3e958b-8740-473c-a84e-0164eaafd656

feat(web): show pool type on pool list

---

apps/web/app/(core)/layout.tsx
libs/web/src/components/common/header-new.tsx
libs/web/src/components/common/toggle-mode.tsx
libs/web/src/core/providers/Providers.tsx

feat(web): mir-454 dark mode

---

libs/web/src/components/pages/view-position-page/components/PositionView/desktop-position-view.tsx

Add mock data to positions view page

feat(web): mir-231 positions view page

---

libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/AddLiquidityDialog.tsx
libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/V2LiquidityConfig.tsx
libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/__tests__/calculateBinLiquidity.test.ts
libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/__tests__/liquidityDistributionGenerator.test.ts
libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/__tests__/liquidityDistributionUtils.test.ts
libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/liquidityDistributionGenerator.ts
libs/web/src/components/pages/add-liquidity-page/components/AddLiquidity/liquidityDistributionUtils.ts
libs/web/src/components/pages/liquidity-page/components/Positions/Positions.tsx
libs/web/src/hooks/useAddLiquidityV2.ts
libs/web/src/hooks/useLiquidityFormV2Integration.ts
libs/web/src/utils/constants.ts

Note
* Moved this PR from #465 
* Renamed branch name

feat(web): mir-421 add liquidity

---

libs/meshwave-ui/alert/alert.tsx
libs/meshwave-ui/alert/index.tsx
libs/web/src/components/pages/bin-liquidity/remove-bin-liquidity.tsx
libs/web/styles.css

Show info text in an alert box
before
after

feat(web): mir-425 liquidity removal
